import { existsSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import type { Db } from './connection.js';

/**
 * Migrations live in `kalshi-trader/app/migrations` (generated by drizzle-kit from src/db/schema.ts).
 * Both `src/db` and `dist/db` sit two levels below the app root, so this resolves in dev and in builds.
 *
 * Up: Drizzle's own migrator (`__drizzle_migrations`, one transaction for all pending migrations).
 * Down: `migrations/down/<tag>.sql`, hand-written per migration; rolling back removes the migration's
 * row from `__drizzle_migrations` in the same transaction, so a later `up` re-applies it.
 */
export const MIGRATIONS_DIR = resolve(import.meta.dirname, '../../migrations');
export const MIGRATIONS_TABLE = '__drizzle_migrations';

interface JournalEntry {
  idx: number;
  when: number;
  tag: string;
}

export interface MigrationStatus {
  tag: string;
  when: number;
  applied: boolean;
}

function readJournal(dir: string): JournalEntry[] {
  const journal = JSON.parse(readFileSync(join(dir, 'meta/_journal.json'), 'utf8')) as {
    entries: JournalEntry[];
  };
  return [...journal.entries].sort((a, b) => a.when - b.when);
}

function appliedMillis(db: Db): number[] {
  const exists = db.sqlite
    .prepare("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?")
    .get(MIGRATIONS_TABLE);
  if (!exists) return [];
  const rows = db.sqlite
    .prepare(`SELECT created_at FROM "${MIGRATIONS_TABLE}" ORDER BY created_at DESC`)
    .all() as { created_at: number | string }[];
  return rows.map((r) => Number(r.created_at));
}

/** Every migration in the journal and whether it is applied, oldest first. */
export function migrationStatus(db: Db, dir = MIGRATIONS_DIR): MigrationStatus[] {
  const applied = new Set(appliedMillis(db));
  return readJournal(dir).map((e) => ({ tag: e.tag, when: e.when, applied: applied.has(e.when) }));
}

/** Applies every pending migration in one transaction. Returns the tags that were applied. */
export function migrateUp(db: Db, dir = MIGRATIONS_DIR): string[] {
  const before = new Set(appliedMillis(db));
  migrate(db.orm, { migrationsFolder: dir, migrationsTable: MIGRATIONS_TABLE });
  return readJournal(dir)
    .filter((e) => !before.has(e.when))
    .map((e) => e.tag);
}

/**
 * Rolls back the `steps` most recent applied migrations (newest first), each in its own
 * transaction. Returns the tags that were rolled back. Throws if a down file is missing or fails;
 * the failing migration stays applied.
 */
export function migrateDown(db: Db, steps = 1, dir = MIGRATIONS_DIR): string[] {
  const journal = readJournal(dir);
  const rolledBack: string[] = [];
  for (const when of appliedMillis(db).slice(0, steps)) {
    const entry = journal.find((e) => e.when === when);
    if (!entry) throw new Error(`applied migration created_at=${when} is not in the journal`);
    const downFile = join(dir, 'down', `${entry.tag}.sql`);
    if (!existsSync(downFile)) throw new Error(`no down migration for ${entry.tag} (${downFile})`);
    const statements = readFileSync(downFile, 'utf8')
      .split('--> statement-breakpoint')
      .filter((s) => s.replace(/--.*$/gm, '').trim().length > 0);
    db.sqlite.transaction(() => {
      for (const stmt of statements) db.sqlite.exec(stmt);
      db.sqlite.prepare(`DELETE FROM "${MIGRATIONS_TABLE}" WHERE created_at = ?`).run(when);
    })();
    rolledBack.push(entry.tag);
  }
  return rolledBack;
}
